blog/apps/noticias/urls.py
from django.urls import path
from . import views

app_name='noticias'

urlpatterns = [
    path('', views.ListarNoticias, name='listar'),
    path('detalle/<int:pk>', views.DetalleNoticia, name='detalle'),
]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings  
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Home, name='home'),
    path('nosotros/', views.Nosotros, name='nosotros'),
    path('noticias/', include('apps.noticias.urls')),
    path('contacto/', views.Contacto, name='contacto'),
    # parametro 1 texto de la url
    # parametro 2 vista que se ejecuta
    # parametro 3 nombre de la url
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/apps/noticias/models.py
from django.db import models

# Create your models here.
class Categoria(models.Model):
    nombre = models.CharField(max_length = 30)

    def  __str__(self):
        return self.nombre
    
class Noticia(models.Model):
    titulo = models.CharField(max_length = 50)
    contenido = models.TextField()
    #imagen requiere pillow
    imagenes = models.ImageField(upload_to='noticias')
    fecha_publicacion = models.DateTimeField(auto_now_add=True)
    categoria_noticia= models.ForeignKey(Categoria, on_delete= models.SET_NULL, null=True)

    def  __str__(self):
        return self.titulo

blog/apps/usuarios/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class Usuario(AbstractUser):
    pass

blog/apps/noticias/views.py
from django.shortcuts import render
from .models import Noticia, Categoria

# Create your views here.
def ListarNoticias(request):
    contexto = {}
    id_categoria = request.GET.get("id", None)

    if id_categoria:
        n = Noticia.objects.filter(categoria_noticia=id_categoria)
    else:
        n = Noticia.objects.all()

    #filtrar por antiguedad asc 
    antiguedad_asc = request.GET.get("antiguedad_asc")
    if antiguedad_asc:
        n = Noticia.objects.all().order_by('fecha_publicacion')
    
    #filtrar por antiguedad des 
    antiguedad_desc = request.GET.get("antiguedad_desc")
    if antiguedad_desc:
        n = Noticia.objects.all().order_by('-fecha_publicacion')

    #filtrar por orden alfabetico asc
    orden_asc = request.GET.get("orden_asc")
    if orden_asc:
        n = Noticia.objects.all().order_by('titulo')
    
    #filtrar por orden alfabetico desc
    orden_desc = request.GET.get("orden_desc")
    if orden_desc:
        n = Noticia.objects.all().order_by('-titulo')


    cat = Categoria.objects.all().order_by('nombre')
    contexto['noticias'] = n
    contexto['categorias'] = cat 
    
    return render (request, 'noticias/listar.html', contexto)

def DetalleNoticia(request, pk):
    contexto = {}

    n = Noticia.objects.get(pk = pk)
    contexto['noticias'] = n
    
    return render (request, 'noticias/detalle.html', contexto)

blog/apps/usuarios/views.py
from django.shortcuts import render

# Create your views here.

blog/blog/views.py
from django.shortcuts import render

def Home(request):
    return render (request, 'home.html')

def Nosotros(request):
    return render(request, 'nosotros.html')

def Contacto(request):
    return render(request, 'contacto.html')

blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <title>Mi Blog {% block titulo %}{% endblock titulo %} </title>
</head>
<body class='contenedor'> 
    {% block contenido %}

    {% endblock contenido %}
    <a href="{% url 'nosotros' %}">IR A NOSOTROS</a>
    <a href="{% url 'home' %}">VOLVER</a>
    <a href="{% url 'noticias:listar' %}">NOTICIAS</a>
</body>
</html>

blog/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block titulo %}Home{% endblock titulo %}  
{% block contenido %}
    <h1>Hola mundo</h1>
{% endblock contenido %}

blog/templates/nosotros.html
{% extends 'base.html' %}
{% load static %}
{% block titulo %}Home{% endblock titulo %}  
{% block contenido %}
    <h2>Este es el home provisorio</h2>
{% endblock contenido %}

blog/templates/noticias/detalle.html
{% extends 'base.html' %}
{% load static %}
{% block titulo %}Noticias{% endblock titulo %}
{% block contenido%}
    <h2>Mi noticia detallada</h2>

    <img src="{{noticias.imagenes.url}}" width="30%">  
    <p>{{noticias.titulo}}</p>
    <p>{{noticias.contenido}}</p>
    <p>{{noticias.fecha_publicacion}}</p>
    <p>{{noticias.categoria_noticia}}</p>
    <br>
    <a href="{% url 'noticias:listar' %}">VOLVER</a>

{% endblock contenido %}

blog/templates/noticias/listar.html
{% extends 'base.html' %}
{% load static %}
{% block titulo %}Noticias{% endblock titulo %}
{% block contenido%}
    <h2>Aquí están las noticias</h2>
    <div class='submenu'>
        <a href="{% url 'noticias:listar' %}">TODAS</a>
        {% for cat in categorias %}
            <a href="?id={{cat.pk}} ">{{cat.nombre}} </a>
        {% endfor %}   
        <a href="?antiguedad_asc=1">Mas antiguas primero</a>
        <a href="?antiguedad_desc=1">Mas nuevas primero</a>
        <a href="?orden_asc=1">a-z</a>
        <a href="?orden_desc=1">z-a</a>
    </div>
    {% for noticias in noticias %}
        <h3><a href="{% url 'noticias:detalle' noticias.pk %}">Titulo: {{noticias.titulo}}</h3></a>
        <img src="{{noticias.imagenes.url}}" width="10%">
        <br>
    {% endfor %}

{% endblock contenido %}